name: build oc.user.nvidia

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [dispatch-from-oc.user.18.04]
jobs:
  main:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps: 
    - name: Clone repository
      run: |
        rm -rf ..?* .[!.]* *
        git clone "https://${{ secrets.USER_NAME }}:${{ secrets.TOKEN }}@github.com/abcdesktopio/oc.user.nvidia.git" .
        git -c http.extraheader="Authorization: basic ${{ secrets.TOKEN }}" submodule update --init --recursive --remote
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

  
    - name: Build image abcdesktopio/oc.user.nvidia
      env:
          # set the release to build
          BASE_IMAGE_RELEASE: 18.04
          BASE_NVIDIA_IMAGE: ubuntu1804
          BASE_IMAGE: abcdesktopio/oc.user
      run: |
        echo "Building image oc.user.nvidia.$BASE_IMAGE_RELEASE"
        docker build . -t abcdesktopio/oc.user.nvidia.$BASE_IMAGE_RELEASE:dev  --file Dockerfile --build-arg BASE_NVIDIA_IMAGE:$BASE_NVIDIA_IMAGE --build-arg BASE_IMAGE_RELEASE:$BASE_IMAGE_RELEASE --build-arg BASE_IMAGE=$BASE_IMAGE.$BASE_IMAGE_RELEASE --build-arg TAG:dev
        
    - name: Push image abcdesktopio/oc.user.nvidia.18.04
      env:
          BASE_IMAGE_RELEASE: 18.04
      run: |
        docker push abcdesktopio/oc.user.nvidia.$BASE_IMAGE_RELEASE:dev
        
    - name: Build image abcdesktopio/oc.user.nvidia.20.04
      env:
          # set the release to build
          BASE_IMAGE_RELEASE: 20.04
          BASE_NVIDIA_IMAGE: ubuntu2004
      run: |
        echo "Building image oc.user.nvidia.$BASE_IMAGE_RELEASE"
        docker build . -t abcdesktopio/oc.user.nvidia.$BASE_IMAGE_RELEASE:dev  --file Dockerfile --build-arg BASE_NVIDIA_IMAGE:$BASE_NVIDIA_IMAGE --build-arg BASE_IMAGE_RELEASE:$BASE_IMAGE_RELEASE --build-arg BASE_IMAGE=abcdesktopio/oc.software.$BASE_IMAGE_RELEASE --build-arg TAG:dev

    - name: Push image abcdesktopio/oc.user.nvidia.20.04
      env:
          BASE_IMAGE_RELEASE: 20.04
      run: |
        docker push abcdesktopio/oc.user.nvidia.$BASE_IMAGE_RELEASE:dev
   
 
